name: Sonar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
            
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.700
    - name: Test
      env:
        NETCORE2_TEST_PROJECT: Mastercard.Developer.XMLSignVerify.Core/XMLSignVerifyTest/XMLSignVerifyTest.csproj
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        export PATH="$PATH:$HOME/.dotnet/tools"
        dotnet tool install --global dotnet-sonarscanner
        
        dotnet sonarscanner begin \
          /k:"Mastercard_xmlsignverify-core-csharp" \
          /n:"xmlsignverify-core-csharp" \
          /o:"mastercard" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.login="$SONAR_TOKEN" \
          /d:sonar.cs.vstest.reportsPaths="./Mastercard.Developer.XMLSignVerify.Core/XMLSignVerifyTest/bin/tests.trx" \
          /d:sonar.cs.opencover.reportsPaths="./Mastercard.Developer.XMLSignVerify.Core/XMLSignVerifyTest/bin/coverage.xml"
        
        dotnet test $NETCORE2_TEST_PROJECT -c Release -l:"trx;LogFileName=tests.trx" -r:"bin/" /p:CollectCoverage=true /p:CoverletOutputFormat="opencover" /p:CoverletOutput="bin/coverage.xml"
        dotnet publish $NETCORE2_TEST_PROJECT -c Release
        dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
